services:
  postgres:
    image: postgres:13
    container_name: nova-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nova-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: nova-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./themes:/opt/keycloak/themes
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: start-dev
    networks:
      - nova-network

  nova-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nova-backend
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_ADMIN_USERNAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./themes:/app/themes
    ports:
      - "8090:8090"
    depends_on:
      - keycloak
    networks:
      - nova-network

  nova-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nova-frontend
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8090
    ports:
      - "8000:8000"
    depends_on:
      - nova-backend
    networks:
      - nova-network

  demo-sub-app:
    build:
      context: ./demo-sub-app
      dockerfile: Dockerfile
    container_name: demo-sub-app
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"
    networks:
      - nova-network

volumes:
  postgres_data:
  keycloak_data:

networks:
  nova-network:
    driver: bridge