server:
  port: 8090

spring:
  application:
    name: nova-iam-backend
  profiles:
    active: local

# Monitoring and Health Checks
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

keycloak:
  server-url: http://localhost:8080
  admin:
    realm: master
    username: admin
    password: admin
  themes:
    path: ./themes
    
logging:
  level:
    com.nova.iam: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %X{traceId} - %logger{36} - %msg%n'

---
spring:
  config:
    activate:
      on-profile: docker

keycloak:
  server-url: http://keycloak:8080
  themes:
    path: /app/themes